language: minimal
sudo: required
services:
- docker
env:
  global:
  - DOCKER_IMAGE=norsknettarkiv/k8s-util
  - DOCKER_TAG=${TRAVIS_BRANCH}
  - secure: ZVBMqNWr0u3EQ5XDA7fbk8TyiFd5IGZSZ3U64BjTq7U70xHZP90NmrTglp1kjx1Aw8xYE3K0uA9yaNCrBd2OBBE8W5TDpPo0wuTyFPg9eNB3xY7TV++KwHYVnhQoNDOaTOSc0sJwh3Ju5dkasw2Y8nGWTPCch+Eo72NraPGHpQc0k7icdRT8Ygo9jH6D6gqDWRk4SKinpQZXi8KIZTbwRnHskZIvph4HZlVJcYbLOJ3cUkDlCRzzfATDO+695YdBLNMd1sRSBOVAoSuApZN+PgKk67MdflGP6J7guuVVdCcQXR+RlGrNKwNEk3c3EghYKQCDfWU1JjsK9NwM3ptByMPCBZILgbUxw/IL42qihGhiygPeSenlwi8+fTwy2w9lNVG0U2kdmHmyC2R0Lmb9t7TnT7o5BR6l0CeqUonM8qzH3wdcd8IaznaLYG+7x978/ST8ybLtviw3XY+c5op9CIlK7QhA32nyncT5OJbPYSfMWTgqjyC3MlipStcsvZvCMa0Ro1hoeewXluraUWiftU00YeUwVty0epeA8s72emgQ0NmFNIZDpD+y+tRHmhLkmhzBxNyvwxJF+tpXgSoR28ofddbG6Xphmt/AMRaWiGj0DzeB9v7aLJ58BiEyktedz5APfIhGO18gzafaowJAMmdkhhK7IyRSPhg7+b7kriY=
  - secure: nLsBeuU3DC63aRoTtCiKAAb5u1/kgMJPe2DywZwaPiCZnZKpniytlfLkuWvu69F09w/28B8MohhOKA5rpBua+L7VPwhfTFPqQl7MTyZiBX7DhxjdtvEi361NZFZMTTPysXBqw0+9GB+cLUAknE1jiExdIWjg9liBkCmad+/8eYp/4DVKuZqoIYZngg+NzBlSUoRf7yH3ZCAiXWPpFyOXOyqkWdGoOnvfBwwfpaBC9NxA4VOJuCkBPK3a1/zhGY/a5YP2sXN4zWHkj/lTP6Mwd3GdWmCD6/5gQ2K7BvMPdD1xZCvV9DCC1yBfNQNAvUD+XLQn+LUI56NIRzWU3onBdKunagUueBGU8Epkab2yrlsWuu50SgoBPipd/8c9whzThvkSfhLvP7hf3eOUNlNxnJIY5t+2PrhXkvg5RAmirCY9yGF7nWJ2TV6s7iFsNMPgsPUTqZQnzXw6ivPrfIxi0J1Oc05gOLxyJRf2QOUNoK9MJkyVNyfymRPk2oudaCt4vadbU0PqivjNkwcWyU8F6Y39U4HNC56rRb56cFE1tvTheiL/xC9cDOM1sy38m0K4JL+2mzcBgat8s23fgr2bavZ0FWGTfqVrVcp0yJSRDX3lG8vLS9gWnVKWO8kv0Hh0n4ArCKJ8oWDQZGdyog5jKSlErY7ug+HSUyWM7rBHoS0=
script:
- make
deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master
