language: minimal

sudo: required

services:
- docker

env:
  global:
  - DOCKER_IMAGE=norsknettarkiv/k8s-util
  - DOCKER_TAG=${TRAVIS_BRANCH}
  - secure: qkjYUPG03lkAhzcgQ8svrSIudidFGeX05I7I6FiABgiYHhoeMRZ/218CSxOsl3iAfDvovNyMD42bp5s2TdYcOeZyMg09hCtAcb1J8YV5Wn6VWJyHWzmNlQLub6zl0Q4sNwgBQo0L5sJeUoOK2WgRH+FnaUJ/ZYwO4eAldQCbYwlAhvjSr7hFvsc3DWXX0u8AmT126Hds7j5y4jaNJo5SiuCmTiXjTGqXl15bSfmBlLgmEOYOkDl2v9e/7ZEoRH5EHOrHLJDZmBsXtr8XuURNePXx4tZVxGR3M5CNQ3SOCYkbbcSz+eYJ00RY9llLfJ3i+gaV4FNPQoufNP6HNtRdyXrIVNzTWdbs2TJ5RoqvPxzsHU39pK1ob4EaBiHOpmfvDJqridgXEAhz+7tyNyVyRXS5+hAPirQSxPRTmtMI7fAXtVHayfn+ABfkSuSSvO5D1l0NgiZeTANBQcQskTYxhqxoo9ZaVigdWRogQO4lx7BKb9O8dAPUHA5iBMpJ4aaD1mz/Hs5LAlEVbkDX5nVr+tV49EkuEhdRyGE7MWyEMT01DQ9Wsg1QbD7Ea3v/6ojJ+TuctUqZI6NjYrFwgIUC98W8gqYx6PNUGz7ZRplspPXoCJPyhLiTjqO33QpCPZPvI6hfx+GX1pt3EUD1bfDaz483/LODJ3sP0Vlzlrac4DE=
  - secure: ExnkBWGZt/yJksE+9VRvRYx8avstChUGZvq1gZEZwtM69v7cFYBz5INzlCLz2vLKNHFuOlpkTmoeA85JffSxxY+xNzRDlict0XYRYLtJbTZ99RLNvcr/rJxUMbTaNEixO8yHCgeVOMUpAqieLpGk7RkIB7HKJJTIZ6ZpaKqCMd6UGsZWg+3kt9NVJaQSg651xHycob83VHYDjQ8/YJxOInKHvVkASLtvpn23Wj0Nu1nwhYn32ApaLxLzYPepNbevypSKedJQlyCAk7pmfbhCiBmx+Kq6s1+Tq0ftBY7MfJkbrGLAU5BMtQcwYum5TWn1XOiCoxxmvgV5A0jMJmuLIMKdrWTVF1G+4bL5nXll97GNzyzSY8cELkK0x81930DVWQqyHUUtLuhfpbmXPv0TtAe4bhRWKLrUSCkIpKxuKdV7azefiIKYfm0AHZGpwMpg3Q1SKooZIayCdt3xhFJb6OH7tTb4xT9PQm4DommA3E4QsvSEE/UsrM39tWGT8BcWf1jWl03cwcmjkCPcBuiKEzZ32VlymASRauIKXxSx/Aey/YRkrCFqAMd3R1nTSZcIOeGsldZjkXY1ACYPiiKB5QR3blWfxJDYo2vn81NKQHvSSK5XuRhmIfwTF7U9bD4PV1rNWXpnYY2qVocmNsp9swEk1AbF/z5l0TGGRJ0fI4E=

script:
- make

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch:
      master
